// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD6V9HmocWanPGImpBL9Ea-QmEXcZal5g',
    appId: '1:610918785951:web:a7b464dd570fe694e413aa',
    messagingSenderId: '610918785951',
    projectId: 'notesapp-4f122',
    authDomain: 'notesapp-4f122.firebaseapp.com',
    storageBucket: 'notesapp-4f122.appspot.com',
    measurementId: 'G-79LEBTHVWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMPl35xldAtVq3lZbVLHBeAiFj4g1Uwx0',
    appId: '1:610918785951:android:4ac67325798daa15e413aa',
    messagingSenderId: '610918785951',
    projectId: 'notesapp-4f122',
    storageBucket: 'notesapp-4f122.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOmFKb-jX7FZF_YhOHm_sxN3ok2jLtLZ0',
    appId: '1:610918785951:ios:0972b32108d4e39ae413aa',
    messagingSenderId: '610918785951',
    projectId: 'notesapp-4f122',
    storageBucket: 'notesapp-4f122.appspot.com',
    iosBundleId: 'com.example.notesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOmFKb-jX7FZF_YhOHm_sxN3ok2jLtLZ0',
    appId: '1:610918785951:ios:0972b32108d4e39ae413aa',
    messagingSenderId: '610918785951',
    projectId: 'notesapp-4f122',
    storageBucket: 'notesapp-4f122.appspot.com',
    iosBundleId: 'com.example.notesapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD6V9HmocWanPGImpBL9Ea-QmEXcZal5g',
    appId: '1:610918785951:web:30d340d95ffb4841e413aa',
    messagingSenderId: '610918785951',
    projectId: 'notesapp-4f122',
    authDomain: 'notesapp-4f122.firebaseapp.com',
    storageBucket: 'notesapp-4f122.appspot.com',
    measurementId: 'G-6GM7EBW6Z4',
  );
}
